# Generated by Django 5.1.5 on 2025-01-15 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nutrition",
            "0002_ingredientmodel_measuringunitmodel_recipeitemmodel_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeitemmodel",
            name="ingredient",
        ),
        migrations.AddField(
            model_name="recipeitemmodel",
            name="ingredient",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="nutrition.ingredientmodel",
            ),
            preserve_default=False,
        ),
    ]
