# Generated by Django 5.1.5 on 2025-01-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0004_ingredientmodel_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeitemmodel",
            old_name="measuring_unit_qty",
            new_name="item_measuring_unit_qty",
        ),
        migrations.RemoveField(
            model_name="recipeitemmodel",
            name="measuring_unit",
        ),
    ]
