# Generated by Django 5.1.5 on 2025-01-15 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nutrition",
            "0005_rename_measuring_unit_qty_recipeitemmodel_item_measuring_unit_qty_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientmodel",
            name="source",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="recipemodel",
            name="ingredient",
        ),
        migrations.AddField(
            model_name="recipemodel",
            name="ingredient",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="nutrition.recipeitemmodel",
            ),
            preserve_default=False,
        ),
    ]
