# Generated by Django 5.1.5 on 2025-01-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0006_alter_ingredientmodel_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeitemmodel",
            name="total_ingredient_cholesterol",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=4,
                verbose_name="cholesterol",
            ),
        ),
    ]
