# Generated by Django 5.1.5 on 2025-01-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0007_alter_recipeitemmodel_total_ingredient_cholesterol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeitemmodel",
            name="total_ingredient_calories",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, verbose_name="calories"
            ),
        ),
        migrations.AlterField(
            model_name="recipeitemmodel",
            name="total_ingredient_carbohydrate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, verbose_name="carbohydrate"
            ),
        ),
        migrations.AlterField(
            model_name="recipeitemmodel",
            name="total_ingredient_cholesterol",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, verbose_name="cholesterol"
            ),
        ),
        migrations.AlterField(
            model_name="recipeitemmodel",
            name="total_ingredient_protein",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, verbose_name="proein"
            ),
        ),
        migrations.AlterField(
            model_name="recipeitemmodel",
            name="total_ingredient_saturated_fat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, verbose_name="saturated_fat"
            ),
        ),
        migrations.AlterField(
            model_name="recipeitemmodel",
            name="total_ingredient_total_fat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, verbose_name="total_fat"
            ),
        ),
        migrations.AlterField(
            model_name="recipeitemmodel",
            name="total_ingredient_trans_fat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, verbose_name="trans_fat"
            ),
        ),
    ]
