# Generated by Django 5.1.5 on 2025-01-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0008_alter_recipeitemmodel_total_ingredient_calories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeitemmodel",
            name="total_ingredient_calories",
        ),
        migrations.RemoveField(
            model_name="recipeitemmodel",
            name="total_ingredient_carbohydrate",
        ),
        migrations.RemoveField(
            model_name="recipeitemmodel",
            name="total_ingredient_cholesterol",
        ),
        migrations.RemoveField(
            model_name="recipeitemmodel",
            name="total_ingredient_protein",
        ),
        migrations.RemoveField(
            model_name="recipeitemmodel",
            name="total_ingredient_saturated_fat",
        ),
        migrations.RemoveField(
            model_name="recipeitemmodel",
            name="total_ingredient_total_fat",
        ),
        migrations.RemoveField(
            model_name="recipeitemmodel",
            name="total_ingredient_trans_fat",
        ),
    ]
