# Generated by Django 5.1.5 on 2025-01-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0009_remove_recipeitemmodel_total_ingredient_calories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeitemmodel",
            name="total_ingredient_calories",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=4,
                verbose_name="calories",
            ),
            preserve_default=False,
        ),
    ]
