# Generated by Django 5.1.5 on 2025-01-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0010_recipeitemmodel_total_ingredient_calories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipemodel",
            name="ingredient",
        ),
        migrations.AddField(
            model_name="recipemodel",
            name="ingredient",
            field=models.ManyToManyField(to="nutrition.recipeitemmodel"),
        ),
    ]
