# Generated by Django 5.1.5 on 2025-01-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0013_recipeitemmodel_recipe_item_measuring_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredientmodel",
            name="base_measuring_unit",
        ),
        migrations.RemoveField(
            model_name="ingredientmodel",
            name="measuring_units",
        ),
        migrations.RemoveField(
            model_name="measuringunitmodel",
            name="base_measuring_unit",
        ),
        migrations.RemoveField(
            model_name="measuringunitmodel",
            name="base_unit_multiplier",
        ),
        migrations.AddField(
            model_name="measuringunitmodel",
            name="measuring_unit_abbreviation",
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="measuringunitmodel",
            name="measuring_unit_name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="recipeitemmodel",
            name="total_ingredient_calories",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=4,
                verbose_name="calories",
            ),
        ),
        migrations.AlterField(
            model_name="recipemodel",
            name="source",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="IngredientUnitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_unit_multiplier", models.FloatField()),
                (
                    "base_measuring_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="base_measuring_unit",
                        to="nutrition.measuringunitmodel",
                    ),
                ),
                (
                    "measuring_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measuring_unit",
                        to="nutrition.measuringunitmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ingredientmodel",
            name="measuring_unit",
            field=models.ManyToManyField(to="nutrition.ingredientunitmodel"),
        ),
    ]
