# Generated by Django 5.1.5 on 2025-01-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0015_remove_ingredientmodel_base_measuring_unit_qty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientunitmodel",
            name="unit_multiplier",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingredientmodel",
            name="protein",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, verbose_name="protein"
            ),
        ),
    ]
