# Generated by Django 5.1.5 on 2025-01-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0016_ingredientunitmodel_unit_multiplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipemodel",
            name="recipe_item",
            field=models.ManyToManyField(
                related_name="receita",
                to="nutrition.recipeitemmodel",
                verbose_name="recipe_item",
            ),
        ),
    ]
