# Generated by Django 5.1.5 on 2025-01-16 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0017_alter_recipemodel_recipe_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipemodel",
            name="recipe_item",
        ),
        migrations.AddField(
            model_name="recipeitemmodel",
            name="recipe",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="nutrition.recipemodel",
            ),
            preserve_default=False,
        ),
    ]
