# Generated by Django 5.1.5 on 2025-01-16 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0019_remove_ingredientmodel_measuring_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeitemmodel",
            name="total_ingredient_calories",
        ),
        migrations.AlterField(
            model_name="recipeitemmodel",
            name="recipe_item_measuring_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="nutrition.ingredientunitmodel",
            ),
        ),
    ]
