# Generated by Django 5.1.5 on 2025-01-16 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0020_remove_recipeitemmodel_total_ingredient_calories_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientmodel",
            name="fiber",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=4, verbose_name="fiber"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MealPlanModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=126)),
                (
                    "target_calories",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("target_protein", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "target_carbohydrate",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "target_total_fat",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("target_fiber", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("meal_time", models.DateField()),
                ("notes", models.CharField(max_length=128)),
                (
                    "raw_ingredient",
                    models.ManyToManyField(
                        blank=True, null=True, to="nutrition.ingredientmodel"
                    ),
                ),
                ("recipe", models.ManyToManyField(to="nutrition.recipemodel")),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nutrition.mealplanmodel",
                    ),
                ),
            ],
        ),
    ]
