# Generated by Django 5.1.5 on 2025-01-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngredientModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100, unique=True)),
                (
                    "ingredient_type",
                    models.CharField(
                        blank=True, choices=[("fruit", "Fruit")], max_length=100
                    ),
                ),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="calories"
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="proein"
                    ),
                ),
                (
                    "carbohydrate",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="carbohydrate"
                    ),
                ),
                (
                    "total_fat",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="total_fat"
                    ),
                ),
                (
                    "saturated_fat",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="saturated_fat"
                    ),
                ),
                (
                    "trans_fat",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="trans_fat"
                    ),
                ),
                (
                    "cholesterol",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="cholesterol"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("source", models.CharField(max_length=100, unique=True)),
                ("ingredient", models.ManyToManyField(to="api.ingredientmodel")),
            ],
        ),
    ]
