# Generated by Django 5.1.5 on 2025-01-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipemodel",
            name="ingredient",
        ),
        migrations.DeleteModel(
            name="IngredientModel",
        ),
        migrations.DeleteModel(
            name="RecipeModel",
        ),
    ]
